readingDataPointsFilters:
  - RandomSamplingDataPointsFilter:
      prob: 1
  #- BoundingBoxDataPointsFilter:
      #xMin: -3.0
      #xMax: 20.0
      #yMin: -20.0
      #yMax: 20.0
      
referenceDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:
      knn: 20
  #- BoundingBoxDataPointsFilter:
      #xMin: -0.0
      #xMax: 20.0
      #yMin: -20.0
      #yMax: 20.0      

matcher:
  KDTreeMatcher:
    knn: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.7

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 10
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4

inspector:
  VTKFileInspector:
     baseFileName : vissteps
     dumpDataLinks : 1
     dumpReading : 1
     dumpReference : 1

#logger:
  #FileLogger
